### PR TITLE
RemainAfterExit=yes

### PR DESCRIPTION
**Pull request by adrelanos**

### CODE REVIEW

**Comment by shadeslayer** [comment]
Why do we need this?

**Comment by adrelanos** [comment]
Then it's easier to check the status of those.

Then 'sudo service odroid-boot-services status' shows a nice output with
green color that everything is rights rather than nothing. (Then it's
hard to know if the service was even started or not even enabled for
some reason.)

**Comment by shadeslayer** [comment]
This change doesn't make logical sense to me. The service is meant to be run exactly once and is meant to exit. It is NOT meant linger afterwards which is why I did not set RemainAfterExit to true.

**Comment by adrelanos** [comment]
RemainAfterExit doesn't influence lingering. In systemd terms it only means `shall be considered active even when all its processes exited`. Many `Type=oneshot` systemd units in /lib/systemd/system similar to this are using RemainAfterExit=true.

Here is an example using RemainAfterExit=true.

```
sudo service systemd-random-seed status
```
```
● systemd-random-seed.service - Load/Save Random Seed
   Loaded: loaded (/lib/systemd/system/systemd-random-seed.service; static)
  Drop-In: /lib/systemd/system/systemd-random-seed.service.d
           └─30_qubes.conf
   Active: active (exited) since Mon 2017-01-09 15:12:02 CET; 2h 54min ago
     Docs: man:systemd-random-seed.service(8)
           man:random(4)
  Process: 408 ExecStart=/usr/lib/qubes/init/qubes-random-seed.sh (code=exited, status=0/SUCCESS)
  Process: 403 ExecStart=/lib/systemd/systemd-random-seed load (code=exited, status=0/SUCCESS)
 Main PID: 408 (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/systemd-random-seed.service

Jan 09 15:12:02 localhost systemd[1]: Started Load/Save Random Seed.
```

-----

Here is an example using RemainAfterExit=false.

```
sudo service lvm2-activation status
```

```
● lvm2-activation.service - Activation of LVM2 logical volumes
   Loaded: loaded (/lib/systemd/system/lvm2-activation.service; enabled)
   Active: inactive (dead) since Mon 2017-01-09 15:12:05 CET; 2h 58min ago
     Docs: man:lvm(8)
           man:vgchange(8)
  Process: 496 ExecStart=/sbin/lvm vgchange -aay --sysinit (code=exited, status=0/SUCCESS)
 Main PID: 496 (code=exited, status=0/SUCCESS
```

Looks better with RemainAfterExit=true.

**Comment by shadeslayer** [comment]
This feels like abusing RemainAfterExit in for minor cosmetic gains. I don't even expect users to check the status of this service.

**Comment by adrelanos** [comment]
What would be a legitimate use case of RemainAfterExit=yes?

I see. That's how I saw RemainAfterExit=yes in my /lib/systemd/system
folder. Feel free to close this one. Not terribly important.

**Comment by shadeslayer** [comment]
IMO RemainAfterExit fits the needs of daemons on whose systemd unit files you should not be able to call start on again.

**Pull request closed without merging**
